spring:
  datasource:
    url: jdbc:mysql://localhost:3306/common?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 5
      max-wait: 6000
      validation-query: select 1
      filters-query: stat,wall
